### ISSUE TITLE
Automate building & distributing fluree/core Docker image

### ISSUE THREAD

**Issue by cap10morgan** [fluree/core#1]
Setup GitHub Actions to build and push a fluree/server Docker image to Docker Hub anytime a version tag is pushed to this repo. Use the version tag (without the leading `v`) as the Docker tag. This should consist of http-api-gateway and db pulled in as library dependencies.

- Have it push the latest main commit to a `main` tag.
- ~~Have it push the git short SHA as a Docker tag too for all main commits.~~ Actually let's hold off on this for now. It really clutters up the tags in Docker Hub.
- The `latest` tag should always be the most recent version (once we release 3.0.0 we should switch this to be the most recent _stable_ release; but we won't have any of those for awhile)

**Comment by aaj3f** [comment]
@cap10morgan @mpoffald -- I've moved this into backlog per some discussion with Marcela and given the plan for our limited alpha community release. One question: should we also include a docker tag for alpha-x / beta-x etc to give some alignment to our tracking of those "versions", or did we decide that, given a release automation for all merges into main, this is ultimately irrelevant and we're fine with just `:latest` + `:[git commit sha]`? I don't know that I have a preference one way or the other

**Comment by cap10morgan** [comment]
My opinion is that version numbers and stability indicators (alpha, beta, etc.) are important for external releases. But we should also automate pushing git sha tags for internal usage and for having community members try out changes they're interested in before they get into a formal release.
