### ISSUE TITLE
single where clause using @id map not working

### ISSUE THREAD

**Issue by Jackamus29** [fluree/core#22]
### Description
When using an @id as an object in a where clause and using a map in the select, the subjects are not filtered to just the subjects that refer to that @id, as expected.

This query returns all subjects that have the property `ex:follows`, regardless of following "ex:brian"
```json
{
    "from": "issue/query-vars",
    "select": { "?s": ["*"] },
    "where": [
        ["?s", "ex:follows", { "@id": "ex:brian" }]
    ]
}
```

This query correctly returns only subjects that follow "ex:brian"
```json
{
    "from": "issue/query-vars",
    "select": { "?s": ["*"] },
    "where": [
        ["?s", "ex:follows", "?o"],
        ["?o", "@id", "ex:brian"]
    ]
}
```

This query also works as expected, returning the subject @id for the subjects that follow ex:brian
```json
{
    "from": "issue/query-vars",
    "select": [ "?s" ],
    "where": [
        ["?s", "ex:follows", { "@id": "ex:brian" }]
    ]
}
```

For more context, check this Slack thread
https://fluree-internal.slack.com/archives/C04AA19P3FW/p1692889166045439

**Comment by aaj3f** [comment]
This is stale and has been fixed by updates to the `where` clause
