### ISSUE TITLE
Implement `deleteData`

### ISSUE THREAD

**Issue by aaj3f** [fluree/core#28]
## Description

`deleteData` is to be an acceptable top-level key for updating data in Fluree.

`deleteData` allows JSON-LD-shaped data to describe deletions of facts. If a `deleteData` JSON-LD resolves to expanded triples and those triples exist in the db state, they should be deleted. That is, if the `deleteData` JSON-LD includes `{ "@id": "ex:andrew", "favNums": [13] }` and `["http://example.org/andrew", favNums, 13]` is a triple in the current db state, then that fact should be deleted. Something like the `null` object value should be allowed to delete all facts on a subject-property pair (e.g. `{ "@id": "ex:andrew", "favNums": null }` would delete all values on that subject-property pair)

If SHACL rules existed to, for example, require a value on a property and the deletion would violate that, then it should be rejected.

It should be possible to include `deleteData` with `insertData` or `upsertData` in the same payload, but there should be a specified sequential order to the processing of those mutations (e.g. `deleteData` -> `upsertData` -> `insertData`)

`deleteData` does not need (and maybe should not allow) a `where` key pre-query and populate bindings. Those bindings should not be necessary and are not allowed within the `deleteData` JSON-LD (this will be true for `insertData` and `upsertData` as well)

## Notes

See Dan's notes here: https://gist.github.com/dpetran/be119af28e518fae44a991a6515909ec

**Comment by mpoffald** [comment]
Putting this back in the backlog for now until https://github.com/fluree/core/issues/27 is done -- there's sufficient overlap between the two that it'd be more efficient to wait until that lands.

**Comment by aaj3f** [comment]
Going to close this issue as we've readjudicated that `delete` should support JSON-LD (and so we don't need `delete` and also `deleteData`)
