### ISSUE TITLE
Implement `upsertData`

### ISSUE THREAD

**Issue by aaj3f** [fluree/core#29]
## Description

`upsertData` is to be an acceptable top-level key for updating data in Fluree.

`upsertData` allows JSON-LD-shaped data to describe a set of facts. The resolved facts will be inserted unless data already exists on the subject-property pairs that are described. If so, the behavior will be a retract-and-replace: retraction of all triples on those subject-property pairs and a replace/insert of all the facts submitted in the JSON-LD payload. 

That is, if the `upsertData` JSON-LD includes `{ "@id": "ex:andrew", "favNums": [13] }` and `["http://example.org/andrew", favNums, 8]` is a triple in the current db state, then `["http://example.org/andrew", favNums, 8]` would be retracted and `["http://example.org/andrew", favNums, 13]` would be asserted. 

It should be possible to include `upsertData` with `insertData` or `deleteData` in the same payload, but there should be a specified sequential order to the processing of those mutations (e.g. `deleteData` -> `upsertData` -> `insertData`)

`upsertData` does not need (and maybe should not allow) a `where` key pre-query and populate bindings. Those bindings should not be necessary and are not allowed within the `deleteData` JSON-LD (this will be true for `insertData` and `deleteData` as well)

## Notes

See Dan's notes here: https://gist.github.com/dpetran/be119af28e518fae44a991a6515909ec

**Comment by dpetran** [comment]
This has been superseded by the where ... insert ... delete ... functionality. We may consider upsert in the future but it will not look quite like this proposal.
