### ISSUE TITLE
`@list` Order Preservation is Broken on `server` / Nexus

### ISSUE THREAD

**Issue by Jackamus29** [fluree/core#75]
**Describe the bug**
When inserting a list of values using the `@container` type of `@list`, I expect to get back the same order of values in query results.

**To Reproduce**
1. Create ledger
```json
{
  "ledger": "list-order-test",
  "@context": {
    "ex": "http://example.org/ns/",
    "ex:age": {
      "@container": "@list"
    }
  },
  "insert": [
    {
      "@id": "zeti",
      "ex:age": [97, 19, 97, 19, 97]
    }
  ]
}
```

2. Query
```json
{
  "from": "list-order-test",
  "@context": {
    "ex": "http://example.org/ns/",
    "ex:age": {
      "@container": "@list"
    }
  },
  "selectDistinct": { "?s": ["*"] },
  "where": {
    "@id": "?s",
    "ex:age": "?age"
  }
}
```

**Expected result**
```json
[
  {
    "@id": "zeti",
    "ex:age": [
      97,
      19,
      97,
      19,
      97
    ]
  }
]
```

**Actual result**
```json
[
  {
    "@id": "zeti",
    "ex:age": [
      19,
      19,
      97,
      97,
      97
    ]
  }
]
```

**Comment by aaj3f** [comment]
@Jackamus29 & I confirmed that even the exact test in `db` (https://github.com/fluree/db/blob/1507c85ab3490c4419a65e236183317a2b43196b/test/fluree/db/query/json_ld_basic_test.clj#L131-L149) when issued via `server` does not preserve order in query results.

**Comment by aaj3f** [comment]
Related to fluree/core#74

**Comment by Jackamus29** [comment]
Confirmed fix from https://github.com/fluree/db/pull/720
Thanks @dpetran!
