### ISSUE TITLE
filter doesn't work on variable predicates

### ISSUE THREAD

**Issue by chrisdostert** [fluree/core#93]
When querying with a variable predicate, filter does not work. 

**To Reproduce**
1. transact a subject with a firstName predicate and an object of "Elon"
2. query 
```    
"where": [
    {
        "@id": "?id",
        "?o": "?p"
    },
    [
        "filter",
        "(contains ?p \"Elon\")"
    ]
],
"select": {
    "?id": ["*"]
}
```

**Expected behavior**
Elon is returned

**System (please complete the following information):**
 - Version 3

**Comment by zonotope** [comment]
This has been fixed in https://github.com/fluree/db/pull/746
